---
- name: Install the site
  sudo: yes
  template: >
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/{{ project_name }}-{{ project_env }}.conf
  tags:
    - provision

- name: Enable the site
  sudo: yes
  notify: reload apache
  file: src=/etc/apache2/sites-available/{{ project_name }}-{{ project_env }}.conf path=/etc/apache2/sites-enabled/{{ project_name }}-{{ project_env }}.conf state=link
  tags:
    - provision