language: python
sudo: false
install:
  - pip install tox codecov
services:
  - postgresql
#before_script:
#  - psql -c 'create database postgres;' -U postgres
script:
  - tox
after_success:
  - codecov
