- name: Create Database User
  sudo: true
  sudo_user: postgres
  postgresql_user: >
    user={{ database_user }}
    password={{ database_password }}
    role_attr_flags=CREATEDB,NOSUPERUSER
  tags:
    - provision

- name: Create Database.
  sudo_user: postgres
  postgresql_db: >
    name={{ database_name }}
    owner={{ database_user }}
    login_host=localhost
    login_user={{ database_user }}
    login_password={{ database_password }}
  tags:
    - provision