---
- name: Collect static file
  sudo_user: "{{ project_user }}"
  django_manage: >
    command=collectstatic
    app_path={{ project_root }}/erudit/
    settings=erudit.settings
    virtualenv={{ virtualenv_root }}
  tags:
    - provision
    - update
  notify:
    - reload the project
    - update permissions
    - change file permissions

- name: reload the project
  file: path={{ project_root }}/erudit/erudit/wsgi.py state=touch
  sudo_user: '{{ project_user }}'
  tags:
    - update
    - provision
