---
- name: Pull sources from the repository
  sudo: yes
  git: >
    repo={{ repo_url }}
    dest={{ project_root }}
    version={{ branch }}
    force=yes
    accept_hostkey=yes
  tags:
    - update
    - provision

- name: give ownership to project user
  sudo: true
  file:
    path: "{{ project_root }}"
    owner: "{{ project_user }}"
    group: www-data
    recurse: true
  tags:
    - testperms
    - update
    - provision
