---
- name: Install the required python packages
  sudo: yes
  apt: >-
    pkg={{ item }}
    state=latest
  with_items:
    - build-essential
    - git
    - python3-dev
    - python3-setuptools
    - python-virtualenv
    - python3-virtualenv
    - python3-pip
  tags:
    - provision